modLoader = "javafml"
loaderVersion = "[44,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "magnetosphere"
version = "${version}"
displayName = "Magnetosphere"
authors = "ebo2022"
description = '''
'''
#logoFile = ""

[[dependencies.magnetosphere]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.magnetosphere]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"