modLoader = "javafml"
loaderVersion = "[${forge_major_version},)"
issueTrackerURL = "https://github.com/teamauroramods/${archives_base_name}/issues"
license = "LGPLv3"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = "${mod_description}"
logoFile = "${mod_id}.logo.png"
authors = "Team Aurora"
credits = "ebo2022"
displayURL= "https://discord.gg/VzXSCFp"

[modproperties.${mod_id}]
catalogueImageIcon="${mod_id}.icon.png"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_major_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "AFTER"
side = "BOTH"