package com.teamaurora.magnetosphere.api.registry.v1;

import net.minecraft.commands.synchronization.ArgumentTypeInfo;
import net.minecraft.core.particles.ParticleType;
import net.minecraft.core.registries.Registries;
import net.minecraft.sounds.SoundEvent;
import net.minecraft.stats.StatType;
import net.minecraft.world.effect.MobEffect;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.ai.attributes.Attribute;
import net.minecraft.world.entity.ai.memory.MemoryModuleType;
import net.minecraft.world.entity.ai.sensing.SensorType;
import net.minecraft.world.entity.ai.village.poi.PoiType;
import net.minecraft.world.entity.decoration.PaintingVariant;
import net.minecraft.world.entity.npc.VillagerProfession;
import net.minecraft.world.entity.schedule.Activity;
import net.minecraft.world.entity.schedule.Schedule;
import net.minecraft.world.inventory.MenuType;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.alchemy.Potion;
import net.minecraft.world.item.crafting.RecipeSerializer;
import net.minecraft.world.item.crafting.RecipeType;
import net.minecraft.world.item.enchantment.Enchantment;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.chunk.ChunkStatus;
import net.minecraft.world.level.levelgen.carver.WorldCarver;
import net.minecraft.world.level.levelgen.feature.Feature;
import net.minecraft.world.level.levelgen.feature.foliageplacers.FoliagePlacerType;
import net.minecraft.world.level.levelgen.feature.stateproviders.BlockStateProviderType;
import net.minecraft.world.level.levelgen.feature.treedecorators.TreeDecoratorType;
import net.minecraft.world.level.material.Fluid;

public interface StandardRegistries {
    PlatformRegistry<Block> BLOCKS = RegistryManager.getRegistry(Registries.BLOCK);
    PlatformRegistry<Fluid> FLUIDS = RegistryManager.getRegistry(Registries.FLUID);
    PlatformRegistry<Item> ITEMS = RegistryManager.getRegistry(Registries.ITEM);
    PlatformRegistry<MobEffect> MOB_EFFECTS = RegistryManager.getRegistry(Registries.MOB_EFFECT);
    PlatformRegistry<SoundEvent> SOUND_EVENTS = RegistryManager.getRegistry(Registries.SOUND_EVENT);
    PlatformRegistry<Potion> POTIONS = RegistryManager.getRegistry(Registries.POTION);
    PlatformRegistry<Enchantment> ENCHANTMENTS = RegistryManager.getRegistry(Registries.ENCHANTMENT);
    PlatformRegistry<EntityType<?>> ENTITY_TYPES = RegistryManager.getRegistry(Registries.ENTITY_TYPE);
    PlatformRegistry<BlockEntityType<?>> BLOCK_ENTITY_TYPES = RegistryManager.getRegistry(Registries.BLOCK_ENTITY_TYPE);
    PlatformRegistry<ParticleType<?>> PARTICLE_TYPES = RegistryManager.getRegistry(Registries.PARTICLE_TYPE);
    PlatformRegistry<MenuType<?>> MENU_TYPES = RegistryManager.getRegistry(Registries.MENU);
    PlatformRegistry<PaintingVariant> PAINTING_VARIANTS = RegistryManager.getRegistry(Registries.PAINTING_VARIANT);
    PlatformRegistry<RecipeType<?>> RECIPE_TYPES = RegistryManager.getRegistry(Registries.RECIPE_TYPE);
    PlatformRegistry<RecipeSerializer<?>> RECIPE_SERIALIZERS = RegistryManager.getRegistry(Registries.RECIPE_SERIALIZER);
    PlatformRegistry<Attribute> ATTRIBUTES = RegistryManager.getRegistry(Registries.ATTRIBUTE);
    PlatformRegistry<StatType<?>> STAT_TYPES = RegistryManager.getRegistry(Registries.STAT_TYPE);
    PlatformRegistry<ArgumentTypeInfo<?, ?>> COMMAND_ARGUMENT_TYPES = RegistryManager.getRegistry(Registries.COMMAND_ARGUMENT_TYPE);
    PlatformRegistry<VillagerProfession> VILLAGER_PROFESSIONS = RegistryManager.getRegistry(Registries.VILLAGER_PROFESSION);
    PlatformRegistry<PoiType> POI_TYPES = RegistryManager.getRegistry(Registries.POINT_OF_INTEREST_TYPE);
    PlatformRegistry<MemoryModuleType<?>> MEMORY_MODULE_TYPES = RegistryManager.getRegistry(Registries.MEMORY_MODULE_TYPE);
    PlatformRegistry<SensorType<?>> SENSOR_TYPES = RegistryManager.getRegistry(Registries.SENSOR_TYPE);
    PlatformRegistry<Schedule> SCHEDULES = RegistryManager.getRegistry(Registries.SCHEDULE);
    PlatformRegistry<Activity> ACTIVITIES = RegistryManager.getRegistry(Registries.ACTIVITY);
    PlatformRegistry<WorldCarver<?>> WORLD_CARVERS = RegistryManager.getRegistry(Registries.CARVER);
    PlatformRegistry<Feature<?>> FEATURES = RegistryManager.getRegistry(Registries.FEATURE);
    PlatformRegistry<ChunkStatus> CHUNK_STATUS = RegistryManager.getRegistry(Registries.CHUNK_STATUS);
    PlatformRegistry<BlockStateProviderType<?>> BLOCK_STATE_PROVIDER_TYPES = RegistryManager.getRegistry(Registries.BLOCK_STATE_PROVIDER_TYPE);
    PlatformRegistry<FoliagePlacerType<?>> FOLIAGE_PLACER_TYPES = RegistryManager.getRegistry(Registries.FOLIAGE_PLACER_TYPE);
    PlatformRegistry<TreeDecoratorType<?>> TREE_DECORATOR_TYPES = RegistryManager.getRegistry(Registries.TREE_DECORATOR_TYPE);
}
